# Generated by Django 6.0.4 on 2026-05-03 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_kwh', models.FloatField(default=0)),
                ('fuel_litres', models.FloatField(default=0)),
                ('lpg_cylinders', models.FloatField(default=0)),
                ('travel_km', models.FloatField(default=0)),
                ('waste_kg', models.FloatField(default=0)),
                ('total_emission', models.FloatField(default=0)),
                ('carbon_credits', models.FloatField(default=0)),
                ('estimated_cost', models.FloatField(default=0)),
                ('electricity_emission', models.FloatField(default=0)),
                ('fuel_emission', models.FloatField(default=0)),
                ('lpg_emission', models.FloatField(default=0)),
                ('travel_emission', models.FloatField(default=0)),
                ('waste_emission', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
